// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef PURPOSE_VERSION_H
#define PURPOSE_VERSION_H

#define PURPOSE_VERSION_STRING "5.107.0"
#define PURPOSE_VERSION_MAJOR 5
#define PURPOSE_VERSION_MINOR 107
#define PURPOSE_VERSION_PATCH 0
#define PURPOSE_VERSION ((5<<16)|(107<<8)|(0))

#endif
