'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2022-02-19
.\"    Manual: Okular gebruikershandleiding
.\"    Source: KDE Gear Okular 22.04
.\"  Language: Dutch
.\"
.TH "\FBOKULAR\FR" "1" "2022\-02\-19" "KDE Gear Okular 22.04" "Okular gebruikershandleiding"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NAME"
okular \- een universele documentviewer

.SH "SAMENVATTING"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIOkular\-opties\fR]  [\fIURL\fR] 



.SH "BESCHRIJVING"
.PP
\fBokular\fR
is bedoeld om documenten in verschillende formaten te tonen\&.



.SH "OKULAR\-OPTIES"



.PP
\fB\-p, \-\-page \fR\fB\fInummer\fR\fR
.RS 4



Open een gegeven pagina in het document\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Document in presentatiemodus starten\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Met afdrukdialoog beginnen\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Met afdrukdialoog beginnen en na afdrukken beëindigen\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Controle over "unieke sessie"\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Stelt u in staat om te voorkomen dat Okular het venster vooraan brengt na de start\&.

.RE
.PP
\fB\-\-find \fR\fB\fItekenreeks\fR\fR
.RS 4



Een tekenreeks zoeken in de tekst\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fItekenreeks\fR\fR
.RS 4



Stelt het externe commando voor de bewerker\&. U kunt het niet instellen in een al actief exemplaar van Okular\&. Merk op dat
\fB\-\-unique\fR
niet wordt ondersteund bij instellen van het commando voor de bewerker op de opdrachtregel\&.

.RE


.SH "ARGUMENTEN"


.PP
\fBURL\fR
.RS 4



Een adres van het te openen document\&. Voor PDF, kan het worden gegeven als
\fIdocumentnaam\fR#\fIbenoemde_bestemming\fR
waar
\fIbenoemde_bestemming\fR
een specifieke benoemde bestemming ingebed in het document\&.

.RE


.SH "TERUGKOPPELING"
.PP
Op IRC, irc\&.libera\&.chat #okular of via e\-mail, okular\-devel@kde\&.org of op het web, <\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>\&.


.SH "ZIE OOK"

.RS 4
Meer uitgebreide informatie vindt u in \m[blue]\fBhelp:/okular\fR\m[]\&\s-2\u[1]\d\s+2 (voer deze URL in in Konqueror of voer uit \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Er is ook verdere informatie beschikbaar op \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
Licentie: GNU General Public Version 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTEUR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Okular man page\&.
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
help:/okular
.RS 4
\%help:/kig
.RE
