'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2019-02-14
.\"    Manual: Okular-Benutzerhandbuch
.\"    Source: KDE-Anwendungen Okular 1.7
.\"  Language: German
.\"
.TH "\FBOKULAR\FR" "1" "2019\-02\-14" "KDE-Anwendungen Okular 1.7" "Okular-Benutzerhandbuch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NAME"
okular \- Ein Betrachter für alle Dokumente

.SH "ÜBERSICHT"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIOkular\-Optionen\fR]  [\fIURL\fR] 



.SH "BESCHREIBUNG"
.PP
\fBokular\fR
zeigt Dokumente in verschiedenen Formaten an\&.



.SH "OKULAR\-OPTIONEN"



.PP
\fB\-p, \-\-page \fR\fB\fIzahl\fR\fR
.RS 4



Öffnet die angegebene Seite im Dokument\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Dokumentanzeige im Präsentationsmodus beginnen\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Startet mit dem Druckdialog\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Startet mit dem Druckdialog und wird nach dem Drucken beendet\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Nur eine Instanz des Programms verwenden\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Mit dieser Option startet Okular minimiert in der Kontrollleiste\&.

.RE
.PP
\fB\-\-find \fR\fB\fIstring\fR\fR
.RS 4



Sucht eine Zeichenfolge im Text\&.

.RE


.SH "ARGUMENTE"


.PP
\fBURL\fR
.RS 4



Die Adresse des zu öffnenden Dokuments\&. Bei PDF\-Dokumenten kann der Name in der Form
\fIdocument_name\fR#\fInamed_destination\fR
angegeben werden\&. Dabei ist
\fInamed_destination\fR
ein bestimmter benannter Bereich im Dokument\&.

.RE


.SH "RÜCKMELDUNG"
.PP
Im IRC\-Kanal #okular auf irc\&.libera\&.chat, über E\-Mails an die Mailingliste okular\-devel@kde\&.org oder im Internet auf der Seite <\m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]\&\s-2\u[1]\d\s+2>


.SH "SIEHE AUCH"

.RS 4
Weitere ausführliche Dokumentation finden Sie unter \m[blue]\fBhelp:/okular\fR\m[] (geben Sie diese URL entweder im Konqueror ein oder starten Sie \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Weitere Informationen finden Sie auf der Webseite \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
Lizenz: GNU General Public License Version 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Okular\-Benutzerhandbuch
.RE
.SH "FUßNOTEN"
.IP " 1." 4
http://okular.kde.org/
.RS 4
\%https://okular.kde.org/
.RE
.IP " 2." 4
https://okular.kde.org/
.RS 4
\%http://okular.kde.org/
.RE
