'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2022-02-19
.\"    Manual: Okular User's Manual
.\"    Source: KDE Gear Okular 22.04
.\"  Language: English
.\"
.TH "\FBOKULAR\FR" "1" "2022\-02\-19" "KDE Gear Okular 22.04" "Okular User's Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NAME"
okular \- a universal document viewer

.SH "SYNOPSIS"
.HP \w'\fBokular\fR\ 'u

\fBokular\fR
 [\fIOkular\ options\fR]
 [\fIURL\fR]




.SH "DESCRIPTION"
.PP
\fBokular\fR
is aimed to show documents in different formats\&.



.SH "OKULAR OPTIONS"



.PP
\fB\-p, \-\-page \fR\fB\fInumber\fR\fR
.RS 4



Open a given page in the document\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Start the document in presentation mode\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Start with print dialog\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Start with print dialog and exit after printing\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Unique instance control\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Allows to prevent Okular window raising after the start\&.

.RE
.PP
\fB\-\-find \fR\fB\fIstring\fR\fR
.RS 4



Find a string on the text\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fIstring\fR\fR
.RS 4



Sets the external editor command\&. You cannot set the editor command in an already running Okular instance\&. Please note that
\fB\-\-unique\fR
is not supported when setting the editor command at the commandline\&.

.RE


.SH "ARGUMENTS"


.PP
\fBURL\fR
.RS 4



An address of the document to be opened\&. For PDF, can be given as
\fIdocument_name\fR#\fInamed_destination\fR
where
\fInamed_destination\fR
is a particular named destination embedded in the document\&.

.RE


.SH "FEEDBACK"
.PP
On IRC, irc\&.libera\&.chat #okular or via email, okular\-devel@kde\&.org or on the web, <\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>\&.


.SH "SEE ALSO"

.RS 4
More detailed user documentation is available from \m[blue]\fBhelp:/okular\fR\m[]
(either enter this URL into Konqueror, or run
\fB\fBkhelpcenter\fR\fR\fB
\fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
There is also further information available at
\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
License: GNU General Public Version 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTHOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Okular man page\&.
.RE
