// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KPTY_VERSION_H
#define KPTY_VERSION_H

#define KPTY_VERSION_STRING "5.107.0"
#define KPTY_VERSION_MAJOR 5
#define KPTY_VERSION_MINOR 107
#define KPTY_VERSION_PATCH 0
#define KPTY_VERSION ((5<<16)|(107<<8)|(0))

#endif
