'\" t
.\"     Title: \fBokular\fR
.\"    Author: Юрій Чорноіван <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 19 лютого 2022 року
.\"    Manual: Інструкція користувача Okular
.\"    Source: KDE Gear Okular 22.04
.\"  Language: Ukrainian
.\"
.TH "\fBokular\fR" "1" "19 лютого 2022 року" "KDE Gear Okular 22.04" "Інструкція користувача Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "НАЗВА"
okular \- універсальний переглядач документів

.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIпараметри\ Okular\fR]  [\fIадреса\fR] 



.SH "ОПИС"
.PP
\fBokular\fR
призначено для показу документів у різних форматах\&.



.SH "ПАРАМЕТРИ Okular"



.PP
\fB\-p, \-\-page \fR\fB\fIномер\fR\fR
.RS 4



Відкрити у документі вказану сторінку\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Запустити документ в режимі презентації\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Запустити програму з показаним діалоговим вікном друку\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Запустити програму з показаним діалоговим вікном друку і завершити роботу після того, як друк буде завершено\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Інструмент керування унікальністю сеансу\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Надає змогу запобігти підняттю вікна Okular над іншими вікнами після запуску\&.

.RE
.PP
\fB\-\-find \fR\fB\fIрядок\fR\fR
.RS 4



Знайти рядок у тексті\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fIрядок\fR\fR
.RS 4



Встановлює команду зовнішнього редактора\&. Встановити команду редактора у вже запущеному екземплярі Okular не можна\&. Будь ласка, зауважте, якщо редактор визначено у командному рядку, ви не зможете скористатися параметром
\fB\-\-unique\fR\&.

.RE


.SH "АРГУМЕНТИ"


.PP
\fBадреса\fR
.RS 4



Адреса документа, який слід відкрити\&. Для PDF цю адресу можна вказати у форматі
\fIназва_документа\fR#\fIіменоване_призначення\fR,
\fIіменоване_призначення\fR
\(em певне іменоване призначення, вбудоване до документа\&.

.RE


.SH "ЗВОРОТНІЙ ЗВ\(cqЯЗОК"
.PP
За допомогою IRC: irc\&.libera\&.chat #okular або за допомогою електронної пошти: okular\-devel@kde\&.org або за допомогою сторінки у інтернеті: <\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>


.SH "ТАКОЖ ПРОЧИТАЙТЕ"

.RS 4
Докладніша документація для користувачів доступна у \m[blue]\fBhelp:/okular\fR\m[] (введіть цю адресу у поле адреси Konqueror або віддайте команду \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Докладніші відомості можна знайти на сайті \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "АВТОРСЬКІ ПРАВА"
.PP
(c) Wilco Greven, Christophe Devriese, 2002
.PP
(c) Enrico Ros, 2004\(en2005
.PP
(c) Piotr Szymanski, 2005
.PP
(c) Albert Astals Cid, 2004\(en2012
.PP
(c) Pino Toscano, 2006\(en2009
.PP
Умови ліцензування: GNU General Public License, версія 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "АВТОР"
.PP
\fBЮрій Чорноіван\fR <\&yurchor@ukr\&.net\&>
.RS 4
Сторінка man Okular\&.
.RE
