'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2022-02-19
.\"    Manual: Manual del usuario de Okular
.\"    Source: KDE Gear Okular 22.04
.\"  Language: Spanish
.\"
.TH "\FBOKULAR\FR" "1" "2022\-02\-19" "KDE Gear Okular 22.04" "Manual del usuario de Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOMBRE"
okular \- un visor universal de documentos

.SH "SINOPSIS"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIopciones\ de\ Okular\fR]  [\fIURL\fR] 



.SH "DESCRIPCIÓN"
.PP
\fBokular\fR
está pensado para mostrar documentos de diferentes formatos\&.



.SH "OPCIONES DE OKULAR"



.PP
\fB\-p, \-\-page \fR\fB\fInúmero\fR\fR
.RS 4



Abre la página indicada del documento\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Inicia el documento en el modo de presentación\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Iniciar con el diálogo de impresión\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Iniciar con el diálogo de impresión y salir tras imprimir\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Controla una única ejecución\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Hace que Okular impida que su ventana pase al primer plano tras el inicio\&.

.RE
.PP
\fB\-\-find \fR\fB\fItexto\fR\fR
.RS 4



Buscar una cadena en el texto\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fItexto\fR\fR
.RS 4



Define la orden del editor externo\&. No se puede definir la orden del editor externo en una instancia de Okular que ya esté en ejecución\&. Tenga en cuenta que no se puede usar
\fB\-\-unique\fR
al definir la orden del editor externo en la línea de órdenes\&.

.RE


.SH "ARGUMENTOS"


.PP
\fBURL\fR
.RS 4



La dirección del documento a abrir\&. Para PDF se puede indicar como
\fInombre_del_documento\fR#\fIdestino\fR, donde
\fIdestino\fR
es un determinado nombre de destino dentro del documento\&.

.RE


.SH "SUGERENCIAS Y COMENTARIOS"
.PP
En IRC (irc\&.libera\&.chat #okular), por correo electrónico (okular\-devel@kde\&.org) o en la Web (<\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>)\&.


.SH "VEA TAMBIÉN"

.RS 4
Dispone de documentación de usuario más detallada en \m[blue]\fBhelp:/okular\fR\m[] (introduzca esa URL en Konqueror o ejecute \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Dispone de más información en \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
Licencia: Pública General de GNU Versión 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Página man de Okular\&.
.RE
