// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef OKULAR_VERSION_H
#define OKULAR_VERSION_H

#define OKULAR_VERSION_STRING "23.07.70"
#define OKULAR_VERSION_MAJOR 23
#define OKULAR_VERSION_MINOR 7
#define OKULAR_VERSION_PATCH 70
#define OKULAR_VERSION ((23<<16)|(7<<8)|(70))

#endif
