'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2016-11-04
.\"    Manual: Manual de Utilizador do Okular
.\"    Source: Aplicações do KDE Okular 1.0
.\"  Language: Portuguese
.\"
.TH "\FBOKULAR\FR" "1" "2016\-11\-04" "Aplicações do KDE Okular 1.0" "Manual de Utilizador do Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOME"
okular \- um visualizador universal de documentos

.SH "SINOPSE"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIOpções\ do\ Okular\fR]  [\fIURL\fR] 



.SH "DESCRIÇÃO"
.PP
O
\fBokular\fR
pretende mostrar os documentos que existam em vários formatos\&.



.SH "OPÇÕES DO OKULAR"



  .PP
\fB\-p, \-\-page \fR\fB\fInúmero\fR\fR
.RS 4

    
  
Abre uma dada página no documento\&.

  
  .RE
  .PP
\fB\-\-presentation\fR
.RS 4

    
  
Inicia o documento no modo de apresentação\&.

  
  .RE
  .PP
\fB\-\-print\fR
.RS 4

    
  
Inicia com a janela de impressão\&.

  
  .RE
  .PP
\fB\-\-unique\fR
.RS 4

    
  
Controlo de instâncias únicas\&.

  
  .RE
  .PP
\fB\-\-noraise\fR
.RS 4

    
  
Permite apresentar a janela do Okular a elevar\-se após o início\&.

  
  .RE


.SH "ARGUMENTOS"



  .PP
\fBURL\fR
.RS 4

    
  
    O endereço do documento a abrir\&. Para o PDF, pode ser indicado como
\fInome_documento\fR#\fIdestino_com_nome\fR, onde o
\fIdestino_com_nome\fR
é um destino identificado em particular que esteja incorporado no documento\&.

  
  .RE


.SH "REACÇÕES"
.PP
No IRC (irc\&.freenode\&.net #okular), por e\-mail,) okular\-devel@kde\&.org) ou ainda na Web (<\m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]>)


.SH "VEJA TAMBÉM"

.RS 4
Está disponível mais alguma documentação detalhada do utilizador em \m[blue]\fBhelp:/okular\fR\m[] (tanto pode indicar este URL no Konqueror como executar \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Existe também mais informações disponíveis em \m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
\*(AqCopyright\*(Aq (c) 2002 de Wilco Greven, Christophe Devriese
.PP
\*(AqCopyright\*(Aq (c) 2004\-2005 de Enrico Ros
.PP
\*(AqCopyright\*(Aq (c) 2005 de Piotr Szymanski
.PP
\*(AqCopyright\*(Aq (c) 2004\-2012 de Albert Astals Cid
.PP
\*(AqCopyright\*(Aq (c) 2006\-2009 de Pino Toscano
.PP
Licença: Geral Pública da GNU Versão 2 <\m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Página de manual do Okular\&.
.RE
