'\" t
.\"     Title: qt5options
.\"    Author: Watts, Lauri <lauri@kde.org>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 4 de juny de 2016
.\"    Manual: Documentació de la línia d'ordres de les Qt
.\"    Source: Frameworks del KDE Qt 5.4
.\"  Language: Catalan
.\"
.TH "QT5OPTIONS" "7" "4 de juny de 2016" "Frameworks del KDE Qt 5.4" "Documentació de la línia d'ord"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOM"
qt5options \- Opcions comunes de la línia d\*(Aqordres per a totes les aplicacions basades en el joc d\*(Aqeines de les Qt(TM)

.SH "SINOPSI"
.HP \w'\fB\fIAplicació\ Qt\fR\fR\ 'u
\fB\fIAplicació Qt\fR\fR  [\fB\-style=\fR\ \fIestil\fR\ /\ \fB\-style\fR\ \fIestil\fR]  [\fB\-stylesheet=\fR\ \fIfull\ d\*(Aqestil\fR\ /\ \fB\-stylesheet\fR\ \fIfull\ d\*(Aqestil\fR]  [\fB\-widgetcount\fR]  [\fB\-reverse\fR]  [\fB\-qmljsdebugger=\fR\ \fIport\fR]  [\fB\-platform\fR\ \fInom_plataforma[:opcions]\fR]  [\fB\-platformpluginpath\fR\ \fIcamí\fR]  [\fB\-platformtheme\fR\ \fItema_plataforma\fR]  [\fB\-plugin\fR\ \fIconnector\fR]  [\fB\-qwindowgeometry\fR\ \fIgeometria\fR]  [\fB\-qwindowicon\fR\ \fIicona\fR]  [\fB\-qwindowtitle\fR\ \fItítol\fR]  [\fB\-reverse\fR]  [\fB\-session\fR\ \fIsessió\fR]  [\fB\-display\fR\ \fInom_màquina:número_pantalla\fR]  [\fB\-geometry\fR\ \fIgeometria\fR]  [\fB\-dialogs=\fR\ \fI[xp|none]\fR]  [\fB\-fontengine=\fR\ \fIfreetype\fR]  [\fB\-h,\ \-\-help\ i\ \-?\ al\ \fR\fBWindows\(rg\fR]  [\fB\-v\ \-\-version\fR] 



.SH "OPCIONS"


.PP
Les següents opcions s\*(Aqapliquen a totes les aplicacions
Qt(TM):




.PP
\fB\-style=\fR \fIestil\fR / \fB\-style\fR \fIestil\fR
.RS 4


Establir l\*(Aqestil de la
IGU
de l\*(Aqaplicació\&. Els valors possibles dependran de la configuració del sistema\&. Si les
Qt(TM)
han estat compilades amb estils addicionals o si disposeu d\*(Aqestils addicionals com a connectors els quals estaran disponibles per a l\*(Aqopció
\fB\-style\fR
de la línia d\*(Aqordres\&.

.RE
.PP
\fB\-stylesheet=\fR \fIfull d\*(Aqestil\fR / \fB\-stylesheet\fR \fIfull d\*(Aqestil\fR
.RS 4


Estableix el full d\*(Aqestil de l\*(Aqaplicació\&. El valor haurà de ser un camí d\*(Aqaccés a un fitxer que contingui el full d\*(Aqestil\&.
.RE
.PP
\fB\-widgetcount\fR
.RS 4


Imprimeix un missatge de depuració al final sobre el nombre de ginys no destruïts a l\*(Aqesquerra i el nombre màxim de ginys existents, tot alhora\&.
.RE
.PP
\fB\-reverse\fR
.RS 4


Estableix la direcció de la disposició de l\*(Aqaplicació a
Qt::RightToLeft\&. Aquesta opció està destinada a ajudar a depurar i no s\*(Aqha d\*(Aqutilitzar en producció\&. El valor predeterminat és detectat automàticament de la configuració regional de l\*(Aqusuari (vegeu també
QLocale::textDirection())\&.
.RE
.PP
\fB\-qmljsdebugger=\fR \fIport\fR
.RS 4


Activa el depurador de QML/JS amb un port especificat\&. El valor haurà d\*(Aqestar format per port:1234[,bloc], on el bloc és opcional i fa que l\*(Aqaplicació esperi fins que un depurador es connecta amb ella\&.
.RE
.PP
\fB\-platform\fR \fInom_plataforma[:opcions]\fR
.RS 4


Especifica el connector d\*(Aqabstracció de la plataforma
Qt(TM)
(QPA \-Qt Platform Abstraction\-)\&.
.RE
.PP
\fB\-platformpluginpath\fR \fIcamí\fR
.RS 4


Especifica el camí dels connectors a la plataforma\&.
.RE
.PP
\fB\-platformtheme\fR \fItema_plataforma\fR
.RS 4


Especifica el tema de la plataforma\&.
.RE
.PP
\fB\-plugin\fR \fIconnector\fR
.RS 4


Especifica els connectors addicionals a carregar\&. L\*(Aqargument pot aparèixer múltiples vegades\&.
.RE
.PP
\fB\-qwindowgeometry\fR \fIgeometria\fR
.RS 4


Especifica la geometria de la finestra per a la finestra principal emprant la sintaxi de
X11\&. Per exemple: \-qwindowgeometry 100x100+50+50
.RE
.PP
\fB\-qwindowicon\fR \fIicona\fR
.RS 4


Estableix la icona predeterminada de la finestra\&.
.RE
.PP
\fB\-qwindowtitle\fR \fItítol\fR
.RS 4


Estableix el títol de la primera finestra\&.
.RE
.PP
\fB\-session\fR \fIsessió\fR
.RS 4


Restaura l\*(Aqaplicació des d\*(Aquna sessió anterior\&.
.RE
.PP
\fB\-display\fR \fInom_màquina:número_pantalla\fR
.RS 4


Canvia les visualitzacions en
X11\&. Anul\(mdla la variable d\*(Aqentorn
\fBDISPLAY\fR\&.
.RE
.PP
\fB\-geometry\fR \fIgeometria\fR
.RS 4


Especifica la geometria de la finestra per a la finestra principal en
X11\&. Per exemple: \-geometry 100x100+50+50
.RE
.PP
\fB\-dialogs=\fR \fI[xp|none]\fR
.RS 4


Només està disponible per a les plataformes de
Windows\(rg\&. XP utilitza diàlegs a l\*(Aqestil nadiu i cap (none) els desactiva\&.
.RE
.PP
\fB\-fontengine=\fR \fIfreetype\fR
.RS 4


Empra el motor de tipus de lletra FreeType\&.
.RE

.PP
\fB\-h, \-\-help i \-? al \fR\fBWindows\(rg\fR
.RS 4


Imprimeix totes les opcions i la descripció de l\*(Aqaplicació\&.
.RE
.PP
\fB\-v \-\-version\fR
.RS 4


Mostra la cadena sobre la versió de l\*(Aqaplicació\&.
.RE





.SH "VEGEU TAMBÉ"

.PP
\fIkf5options\fR(7)



.SH "AUTORS"

.PP
Pàgina de manual original escrita per en
Watts, Lauri
<lauri@kde\&.org>
.PP
Actualitzada als
Frameworks
5 per en
Lück, Burkhard
<lueck@hube\-lueck\&.de>
.PP
La informació d\*(Aqaquesta pàgina del manual és de la
\m[blue]\fBdocumentació de QApplication\fR\m[]\&\s-2\u[1]\d\s+2, la
\m[blue]\fBdocumentació de QGuiApplication\fR\m[]\&\s-2\u[2]\d\s+2
i la
\m[blue]\fBdocumentació de QCommandLineParser\fR\m[]\&\s-2\u[3]\d\s+2\&.


.SH "AUTORS"
.PP
\fBWatts, Lauri\fR <\&lauri@kde\&.org\&>
.RS 4
Autor.
.RE
.PP
\fBLück, Burkhard\fR <\&lueck@hube\-lueck\&.de\&>
.RS 4
Autor.
.RE
.SH "NOTES"
.IP " 1." 4
documentació de QApplication
.RS 4
\%https://doc.qt.io/qt-5/qapplication.html#QApplication
.RE
.IP " 2." 4
documentació de QGuiApplication
.RS 4
\%https://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication
.RE
.IP " 3." 4
documentació de QCommandLineParser
.RS 4
\%https://doc.qt.io/qt-5/qcommandlineparser.html
.RE
