'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2013-03-09
.\"    Manual: KDE kasutaja käsiraamat
.\"    Source: KDE töökeskkond
.\"  Language: Estonian
.\"
.TH "\FBOKULAR\FR" "1" "2013\-03\-09" "KDE töökeskkond" "KDE kasutaja käsiraamat"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NIMI"
okular \- universaalne dokumentide näitaja

.SH "SüNOPSIS"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIQt\ võtmed\fR]  [\fIKDE\ võtmed\fR]  [\fIOkulari\ võtmed\fR]  [\fIURL\fR] 



.SH "KIRJELDUS"
.PP
\fBokular\fR
on mõeldud eri vormingutes dokumentide näitamiseks\&.



.SH "ÜLDISED VõTMED"



  .PP
\fB\-\-help\fR
.RS 4

  
  
Abiteate näitamine võtmete kohta\&.

  
  .RE
  .PP
\fB\-\-help\-qt\fR
.RS 4

  
  
Qt spetsiifiliste võtmete näitamine\&.

  
  .RE
  .PP
\fB\-\-help\-kde\fR
.RS 4

  
  
KDE spetsiifiliste võtmete näitamine\&.

  
  .RE
  .PP
\fB\-\-help\-all\fR
.RS 4

  
  
Kõigi võtmete näitamine\&.

  
  .RE
  .PP
\fB\-\-author\fR
.RS 4

  
  
Teabe näitamine autori kohta\&.

  
  .RE
  .PP
\fB\-v, \-\-version\fR
.RS 4

  
  
Versiooniteabe näitamine\&.

  
  .RE
  .PP
\fB\-\-license\fR
.RS 4

  
  
Litsentsiteabe näitamine\&.

  
  .RE
  .PP
\fB\-\-\fR
.RS 4

  
  
Võtmete lõpp\&.

  
  .RE


.SH "OKULARI VõTMED"



  .PP
\fB\-p, \-\-page \fR\fB\fInumber\fR\fR
.RS 4

    
  
Määratud lehekülje avamine dokumendis\&.

  
  .RE
  .PP
\fB\-\-presentation\fR
.RS 4

    
  
Dokumendi avamine esitlusrežiimis\&.

  
  .RE
  .PP
\fB\-\-print\fR
.RS 4

    
  
Käivitamine trükkimisdialoogiga\&.

  
  .RE
  .PP
\fB\-\-unique\fR
.RS 4

    
  
"Unikaalse isendi" kontroll\&.

  
  .RE
  .PP
\fB\-\-noraise\fR
.RS 4

    
  
Võimaldab vältida Okulari akna esiletoomist käivitamise järel\&.

  
  .RE


.SH "ARGUMENDID"



  .PP
\fBURL\fR
.RS 4

    
  
    Avatava dokumendi aadress\&. PDF\-dokumentide puhul võib määrata kujul
\fIdokumendi_nimi\fR#\fInimega_sihtkoht\fR, kus
\fInimega_sihtkoht\fR
on konkreetne dokumenti põimitud nimega sihtkoht\&.

  
  .RE


.SH "TAGASISIDE"
.PP
IRC\-s irc\&.freenode\&.net #okular või e\-postiga okular\-devel@kde\&.org või veebis <\m[blue]\fBhttp://okular\&.kde\&.org\fR\m[]>


.SH "VAATA KA"

.PP
Põhjalikumat kasutaja dokumentatsiooni pakub
\m[blue]\fBhelp:/okular\fR\m[]
(kirjuta see
URL
Konquerori või käivita käsuga
\fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.


.SH "AUTORIõIGUS"
.PP
Autoriõigus (c) 2002: Wilco Greven, Christophe Devriese
.PP
Autoriõigus (c) 2004\-2005: Enrico Ros
.PP
Autoriõigus (c) 2005: Piotr Szymanski
.PP
Autoriõigus (c) 2004\-2012: Albert Astals Cid
.PP
Autoriõigus (c) 2006\-2009: Pino Toscano
.PP
Litsents: GNU Üldine Avalik Litsents, versioon 2 <\m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTHOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Okular man page\&.
.RE
