'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 14/02/2019
.\"    Manual: Manual do usuário do Okular
.\"    Source: KDE Applications Okular 1.7
.\"  Language: Portuguese (Brazil)
.\"
.TH "\FBOKULAR\FR" "1" "14/02/2019" "KDE Applications Okular 1.7" "Manual do usuário do Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOME"
okular \- um visualizador de documentos universal

.SH "SINOPSE"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIOpções\ do\ Okular\fR]  [\fIURL\fR] 



.SH "DESCRIçãO"
.PP
\fBokular\fR
tem como objetivo mostrar documentos em vários formatos\&.



.SH "OPçõES DO OKULAR"



.PP
\fB\-p, \-\-page \fR\fB\fInúmero\fR\fR
.RS 4



Abre um documento na página indicada\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Inicia o documento no modo de apresentação\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Inicia com a janela de impressão\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Inicia com a janela de impressão e sai após imprimir\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Controle de instância única\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Permite apresentar a janela do Okular a elevar\-se após o início\&.

.RE
.PP
\fB\-\-find \fR\fB\fItexto\fR\fR
.RS 4



Localiza um termo de pesquisa no texto\&.

.RE


.SH "ARGUMENTOS"


.PP
\fBURL\fR
.RS 4



Endereço do documento a ser aberto\&. Para PDF, pode ser indicado como
\fInome_documento\fR#\fInome_destino\fR
onde
\fInome_destino\fR
é um nome de destino específico incorporado no documento\&.

.RE


.SH "SUGESTõES"
.PP
No IRC, irc\&.freenode\&.net #okular; através de e\-mail, okular\-devel@kde\&.org; ou na página Web, <\m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]>


.SH "VEJA TAMBéM"

.RS 4
A documentação mais detalhada para o usuário está disponível em \m[blue]\fBhelp:/okular\fR\m[] (tanto poderá inserir esta URL no Konqueror, como executar o comando \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Existem mais informações disponíveis em \m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]
.RE

.SH "DIREITOS AUTORAIS"
.PP
Direitos autorais (c) 2002, de Wilco Greven e Christophe Devriese
.PP
Direitos autorais (c) 2004\-2005, de Enrico Ros
.PP
Direitos autorais (c) 2005, de Piotr Szymanski
.PP
Direitos autorais (c) 2004\-2012, de Albert Astals Cid
.PP
Direitos autorais (c) 2006\-2009, de Pino Toscano
.PP
Licença: GNU\-GPL versão 2 <\m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTOR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Página de manual do Okular\&.
.RE
