'\" t
.\"     Title: \fBokular\fR
.\"    Author: Chornoivan, Yuri <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 19 de febrer de 2022
.\"    Manual: Manual d'usuari de l'Okular
.\"    Source: KDE Gear Okular 22.04
.\"  Language: Catalan
.\"
.TH "\FBOKULAR\FR" "1" "19 de febrer de 2022" "KDE Gear Okular 22.04" "Manual d'usuari de l'Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOM"
okular \- un visualitzador universal de documents

.SH "SINOPSI"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIOpcions\ de\ l\*(AqOkular\fR]  [\fIURL\fR] 



.SH "DESCRIPCIÓ"
.PP
L\*(Aq\fBokular\fR
té com a objectiu mostrar documents en formats diferents\&.



.SH "OPCIONS DE L\*(AQOKULAR"



.PP
\fB\-p, \-\-page \fR\fB\fInúmero\fR\fR
.RS 4



Obre una pàgina determinada en el document\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Inicia el document en el mode presentació\&.

.RE
.PP
\fB\-\-print\fR
.RS 4



Inicia amb un diàleg d\*(Aqimpressió\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Inicia amb el diàleg d\*(Aqimpressió i surt després d\*(Aqimprimir\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Control d\*(Aq\(FoInstància única\(Fc\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Permet prevenir l\*(Aqelevació de la finestra de l\*(AqOkular després de l\*(Aqinici\&.

.RE
.PP
\fB\-\-find \fR\fB\fIcadena\fR\fR
.RS 4



Cerca una cadena al text\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fIcadena\fR\fR
.RS 4



Defineix l\*(Aqordre de l\*(Aqeditor extern\&. No es pot definir l\*(Aqordre de l\*(Aqeditor en una instància en execució de l\*(AqOkular\&. Tingueu en compte que no es permet
\fB\-\-unique\fR
quan es defineix l\*(Aqordre de l\*(Aqeditor a la línia d\*(Aqordres\&.

.RE


.SH "ARGUMENTS"


.PP
\fBURL\fR
.RS 4



Una adreça del document a obrir\&. Per a un PDF, podeu indicar\-ho com
\fInom_document\fR#\fInom_destinació\fR, on
\fInom_destinació\fR
serà una destinació concreta amb nom incrustada en el document\&.

.RE


.SH "COMENTARIS"
.PP
A l\*(AqIRC, irc\&.libera\&.chat #okular o mitjançant correu electrònic, okular\-devel@kde\&.org o al lloc web, <\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>\&.


.SH "VEGEU TAMBÉ"

.RS 4
Hi ha disponible documentació d\*(Aqusuari més detallada des de \m[blue]\fBhelp:/okular\fR\m[] (podeu emprar aquest URL al Konqueror o bé executar \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
També hi ha més informació disponible al lloc web \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
Llicència pública general de GNU versió 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTOR"
.PP
\fBChornoivan, Yuri\fR <\&yurchor@ukr\&.net\&>
.RS 4
Pàgina man de l\*(AqOkular\&.
.RE
