'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2022-02-19
.\"    Manual: Manuale utente di Okular
.\"    Source: KDE Gear Okular 22.04
.\"  Language: Italian
.\"
.TH "\FBOKULAR\FR" "1" "2022\-02\-19" "KDE Gear Okular 22.04" "Manuale utente di Okular"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOME"
okular \- un visualizzatore universale di documenti

.SH "SINOSSI"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIopzioni\ di\ Okular\fR]  [\fIURL\fR] 



.SH "DESCRIZIONE"
.PP
\fBokular\fR
ha lo scopo di mostrare documenti in vari formati\&.



.SH "OPZIONI DI OKULAR"



.PP
\fB\-p, \-\-page \fR\fB\fInumero\fR\fR
.RS 4



Apre una pagina specificata del documento\&.

.RE
.PP
\fB\-\-presentation\fR
.RS 4



Apre il documento in modalità presentazione

.RE
.PP
\fB\-\-print\fR
.RS 4



Avvia mostrando la finestra di stampa\&.

.RE
.PP
\fB\-\-print\-and\-exit\fR
.RS 4



Avvia mostrando la finestra di stampa e termina dopo la stampa\&.

.RE
.PP
\fB\-\-unique\fR
.RS 4



Controllo "istanza unica"\&.

.RE
.PP
\fB\-\-noraise\fR
.RS 4



Permette di evitare che la finestra di Okular si rialzi dopo l\*(Aqavvio\&.

.RE
.PP
\fB\-\-find \fR\fB\fIstringa\fR\fR
.RS 4



Trova una stringa nel testo\&.

.RE
.PP
\fB\-\-editor\-cmd \fR\fB\fIstringa\fR\fR
.RS 4



Imposta il comando dell\*(Aqeditor esterno\&. Non puoi impostare il comando dell\*(Aqeditor in un\*(Aqistanza di Okular già in esecuzione\&. Nota come l\*(Aqopzione
\fB\-\-unique\fR
non è supportata quando si imposta il comando dell\*(Aqeditor tramite riga di comando\&.

.RE


.SH "ARGOMENTI"


.PP
\fBURL\fR
.RS 4



L\*(Aqindirizzo del documento da aprire\&. Nel caso di documenti PDF, il nome può essere specificato come
\fInome_documento\fR#\fInome_destinazione\fR, dove
\fInome_destinazione\fR
è l\*(Aqidentificativo di una destinazione presente nel documento\&.

.RE


.SH "SEGNALAZIONI"
.PP
Su IRC, irc\&.libera\&.chat #okular o tramite posta elettronica, okular\-devel@kde\&.org o sul web, <\m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]>\&.


.SH "VEDI ANCHE"

.RS 4
Documentazione utente più dettagliata è disponibile da \m[blue]\fBhelp:/okular\fR\m[] (inserisci questo come URL in Konqueror, o esegui \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Ulteriori informazioni sono disponibili presso \m[blue]\fBhttps://okular\&.kde\&.org/\fR\m[]
.RE

.SH "COPYRIGHT"
.PP
Copyright (c) 2002 Wilco Greven, Christophe Devriese
.PP
Copyright (c) 2004\-2005 Enrico Ros
.PP
Copyright (c) 2005 Piotr Szymanski
.PP
Copyright (c) 2004\-2012 Albert Astals Cid
.PP
Copyright (c) 2006\-2009 Pino Toscano
.PP
Licenza: GNU General Public Version 2 <\m[blue]\fBhttps://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTORE"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Pagina di manuale di Okular\&.
.RE
