// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KWALLET_VERSION_H
#define KWALLET_VERSION_H

#define KWALLET_VERSION_STRING "5.107.0"
#define KWALLET_VERSION_MAJOR 5
#define KWALLET_VERSION_MINOR 107
#define KWALLET_VERSION_PATCH 0
#define KWALLET_VERSION ((5<<16)|(107<<8)|(0))

#endif
