'\" t
.\"     Title: \fBokular\fR
.\"    Author: Yuri Chornoivan <yurchor@ukr.net>
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 09-03-2013
.\"    Manual: Manuel utilisateur de KDE
.\"    Source: Environnement de bureau K
.\"  Language: French
.\"
.TH "\FBOKULAR\FR" "1" "09\-03\-2013" "Environnement de bureau K" "Manuel utilisateur de KDE"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------




.SH "NOM"
okular \- Un afficheur universel de document

.SH "SYNOPSIS"
.HP \w'\fBokular\fR\ 'u
\fBokular\fR  [\fIQt\-options\fR]  [\fIKDE\-options\fR]  [\fIOptions\ Okular\fR]  [\fIURL\fR] 



.SH "DESCRIPTION"
.PP
\fBokular\fR
a pour objectif d\*(Aqafficher des documents de différents formats\&.



.SH "OPTIONS GÉNÉRIQUES"



  .PP
\fB\-\-help\fR
.RS 4

  
  
Affiche l\*(Aqaide pour les options\&.

  
  .RE
  .PP
\fB\-\-help\-qt\fR
.RS 4

  
  
Affiche les options spécifiques de Qt\&.

  
  .RE
  .PP
\fB\-\-help\-kde\fR
.RS 4

  
  
Affiche les options spécifiques de KDE\&.

  
  .RE
  .PP
\fB\-\-help\-all\fR
.RS 4

  
  
Affiche toutes les options\&.

  
  .RE
  .PP
\fB\-\-author\fR
.RS 4

  
  
Affiche les informations sur l\*(Aqauteur\&.

  
  .RE
  .PP
\fB\-v, \-\-version\fR
.RS 4

  
  
Affiche les informations de version\&.

  
  .RE
  .PP
\fB\-\-license\fR
.RS 4

  
  
Affiche les informations de licence\&.

  
  .RE
  .PP
\fB\-\-\fR
.RS 4

  
  
Fin des options\&.

  
  .RE


.SH "OPTIONS POUR OKULAR"



  .PP
\fB\-p, \-\-page \fR\fB\fInombre\fR\fR
.RS 4

    
  
Ouvre une page donnée dans le document\&.

  
  .RE
  .PP
\fB\-\-presentation\fR
.RS 4

    
  
Démarre le document dans le mode de présentation\&.

  
  .RE
  .PP
\fB\-\-print\fR
.RS 4

    
  
Démarrer avec la boîte de dialogue d\*(Aqimpression\&.

  
  .RE
  .PP
\fB\-\-unique\fR
.RS 4

    
  
Contrôle d\*(Aqinstance unique\&.

  
  .RE
  .PP
\fB\-\-noraise\fR
.RS 4

    
  
Permet d\*(Aqempêcher l\*(Aqapparition de la fenêtre d\*(AqOkular après le démarrage\&.

  
  .RE


.SH "ARGUMENTS"



  .PP
\fBURL\fR
.RS 4

    
  
    Une adresse pour le document à ouvrir\&. Pour PDF, peut être donné comme
\fInom\-document\fR#\fIdestination\-nommée\fR
où
\fIdestination\-nommée\fR
est une destination particulière nommée et intégrée dans le document\&.

  
  .RE


.SH "RETOUR D\*(AQINFORMATIONS"
.PP
Sur IRC, irc\&.freenode\&.net #okular ou par courriel, okular\-devel@kde\&.org ou sur Internet <\m[blue]\fBhttp://okular\&.kde\&.org/\fR\m[]>


.SH "VOIR AUSSI"

.PP
Des documentations utilisateur plus détaillées sont disponibles sur
\m[blue]\fBhelp:/okular\fR\m[]
(ou aussi ne saisissant cet
URL
dans
Konqueror
ou lancer
\fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/okular\fR\fR)\&.


.SH "COPYRIGHT"
.PP
Copyright (c) 2002 par Wilco Greven et Christophe Devriese
.PP
Copyright (c) 2004\-2005 par Enrico Ros
.PP
Copyright (c) 2005 par Piotr Szymanski
.PP
Copyright (c) 2004\-2012 par Albert Astals Cid
.PP
Copyright (c) 2006\-2009 par Pino Toscano
.PP
Licence\ \&: GNU General Public Version 2 <\m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\-2\&.0\&.html\fR\m[]>

.SH "AUTEUR"
.PP
\fBYuri Chornoivan\fR <\&yurchor@ukr\&.net\&>
.RS 4
Page \(Fo\ \&man\ \&\(Fc pour Okular\&.
.RE
