Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/karchive' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/kguiaddons' : '@same'
    'frameworks/kdbusaddons' : '@same'
    'frameworks/kservice' : '@same'
    'frameworks/kwindowsystem' : '@same'
    'frameworks/kcrash' : '@same'
    'frameworks/kinit' : '@same'
    'frameworks/kjs' : '@same'
    'frameworks/kconfigwidgets' : '@same'
    'frameworks/kitemviews' : '@same'
    'frameworks/kiconthemes' : '@same'
    'frameworks/knotifications' : '@same'
    'frameworks/kcompletion' : '@same'
    'frameworks/ktextwidgets' : '@same'
    'frameworks/kxmlgui' : '@same'
    'frameworks/kparts' : '@same'
    'frameworks/kio' : '@same'
    'frameworks/kwallet' : '@same'
    'libraries/phonon' : '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kglobalaccel' : '@same'

Options:
  test-before-installing: True
