QT.network_private.VERSION = 5.15.2
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.2 $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.2/QtNetwork
QT.network_private.frameworks =
QT.network_private.depends = core_private network
QT.network_private.uses = openssl
QT.network_private.module_config = v2 internal_module
QT.network_private.enabled_features = openssl-linked openssl system-proxies
QT.network_private.disabled_features = libproxy linux-netlink netlistmgr
QMAKE_INCDIR_OPENSSL = /home/build/inkbox/compiled-binaries/arm-kobo-linux-gnueabihf/arm-kobo-linux-gnueabihf/sysroot//usr/include
QMAKE_LIBS_OPENSSL = -L/home/build/inkbox/compiled-binaries/arm-kobo-linux-gnueabihf/arm-kobo-linux-gnueabihf/sysroot//usr/lib -lssl -lcrypto
QMAKE_LIBS_NETWORK = 
